LambdaCreateIdeaFunctionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: "Lambda-CreateIdeaFunctionRole-${self:provider.stage}"
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action: "sts:AssumeRole"
    Policies:
      - PolicyName: "Lambda-CreateIdeaFunctionRole-${self:provider.stage}-Policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                - "logs:DescribeLogStreams"
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:UpdateItem"
                - "dynamodb:BatchWriteItem"
                - "dynamodb:Query"
              Effect: Allow
              Resource:
                - "arn:aws:logs:*:*:*"
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.ideasTableName}/*'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.usersTableName}/*'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.tagsTableName}'
                - 'Fn::Join':
                    - ':'
                    - - 'arn:aws:dynamodb'
                      - Ref: 'AWS::Region'
                      - Ref: 'AWS::AccountId'
                      - 'table/${self:custom.tagsTableName}/*'
